# Project Euler problem 29: Find the number of distinct terms in the sequence
# generated by a^b where 2 <= a <= 100 and 2 <= b <= 100

sequence = []
for a in range(2,101):
    for b in range(2,101):
        term = a ** b
        if term in sequence:
            continue
        sequence.append(term)

print(len(sequence))

# I am genuinely confused at why some problems are so much easier than others.
# I didn't need to write my own multiplication algorithm using strings for 
# this, nothing of the sort. But whatever, I got my Project Euler problem of
# the day done.